### ISSUE TITLE
Error implementing Django example

### ISSUE THREAD

**Issue by ensignavenger** [theojulienne/PySignals#1]
I have attempted to implement the example in the Django documentation, but I am getting an error:

> > > def my_callback(sender, **kwargs):
> > > ...     print "Request finished!"
> > > ... 
> > > import pysignals
> > > pizza_done = pysignals.Signal(providing_args=["toppings", "size"])
> > > pizza_done.connect(my_callback)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/quickstart/.virtualenvs/py_vgt/lib/python2.7/site-packages/pysignals/dispatcher.py", line 108, in connect
> > >     receiver_module_file = os.path.abspath( sys.modules[receiver.**module**].**file** )
> > > AttributeError: 'module' object has no attribute '**file**'

I seem to get this error anytime I try to connect to a signal.

**Comment by knight-of-ni** [comment]
I know. I know. I'm responding to an 8 year old issue. However, I thought I'd give the example in the Django documentation a try.
The following script was run using the latest pysignals 0.1.3 on Python 3.8:

```python
#!/usr/bin/python

import pysignals

def my_callback(sender, **kwargs):
  print("Request finished!")

pizza_done = pysignals.Signal(providing_args=["toppings", "size"])
pizza_done.connect(my_callback)

pizza_done.send(my_callback, toppings="sausage", size="xl")
```
It produces the expected output "Request finished!".

Feel free to open a new issue if there continues to be a problem.
