### ISSUE TITLE
Update version on pypi

### ISSUE THREAD

**Issue by NL9** [theojulienne/PySignals#5]
The latest version on pypi is 0.1.2 https://pypi.org/project/pysignals/#history

**Comment by knight-of-ni** [comment]
As a secondary participant in this project, I do not have access to update the PySignals project on PyPi.
That would need to be done by @theojulienne. Perhaps he could do that or grant me permission.

**Comment by theojulienne** [comment]
@knight-of-ni happy to add you! What's your PyPi username?

**Comment by knight-of-ni** [comment]
Thank you, sir. 
PyPi username: knight-of-ni

**Comment by knight-of-ni** [comment]
PySignals has been updated on PyPi to the latest, 0.1.4
https://pypi.org/project/pysignals/
